version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3000:80"
    depends_on:
      back-office:
        condition: service_started

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.6
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auto-dungeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "auto-dungeon"]
      interval: 60s
      timeout: 15s
      retries: 5
    restart: unless-stopped
